"""empty message

Revision ID: 77acfb8caba9
Revises: 0763d677d453
Create Date: 2025-11-06 01:17:37.727971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77acfb8caba9'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.String(length=60), nullable=False),
    sa.Column('invoice_number', sa.String(length=60), nullable=False),
    sa.Column('invoice_amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    # ### end Alembic commands ###
